environment: dev
service:
  type: ClusterIP
  scheme: HTTP
  port: 80

# Kong Configs
kongService:
  enabled: true
  type: ExternalName
  origin: istio-ingressgateway.istio-system.svc.cluster.local

apiKongIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/preserve-host: "false"
    konghq.com/https-redirect-status-code: "301"
  hosts:
    api-dev.lumirental.com:
      - /partner-service/
    lumi-api:
      - /partner-service/

vproKongIngress:
  enabled: false

hpa:
  enabled: true
  targetCPUUtilizationPercentage: 80
  TargetAvgMemoryUtilization: 80
replicaCount: 2
maxReplicas: 4

resources:
  requests:
    cpu: 100m
    memory: 700Mi
  limits:
    cpu: 1000m
    memory: 1Gi

environment_variable:
  enabled: true
  data:
      APP_NAME: "lumi-core-partner-service"
      SERVER_PORT: "80"
      SPRING_DATASOURCE_USERNAME: "lumi-core-partner-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://lumi-core-partner-service-rds/lumi-core-partner-service?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
      SPRING_READ_REPLICA_DATASOURCE_USERNAME: "lumi-core-partner-service"
      SPRING_READ_REPLICA_DATASOURCE_URL: "jdbc:mysql://lumi-core-partner-service-rds-ro/lumi-core-partner-service?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
      SPRING_REDIS_HOST: "lumi-core-partner-service-redis"
      SPRING_REDIS_PORT: "6379"

log_alerts:
  enabled: false
